export const GET_ANALYTICS_REQUEST = "GET_ANALYTICS_REQUEST";
export const GET_ANALYTICS_SUCCESS = "GET_ANALYTICS_SUCCESS";
export const GET_ANALYTICS_FAILED = "GET_ANALYTICS_FAILED";
export const GET_PIE_SUCCESS = "GET_PIE_SUCCESS";
export const GET_VERTICAL_SUCCESS = "GET_VERTICAL_SUCCESS";
export const GET_ARABLE_METRIC_SUCCESS= "GET_ARABLE_METRIC_SUCCESS";
export const GET_FOREST_METRIC_SUCCESS= "GET_FOREST_METRIC_SUCCESS";