export const SET_MAP = "SET_MAP";
export const SET_COORDINATES = "SET_COORDINATES";
export const RESET_COORDINATES = "RESET_COORDINATES";
export const TOGGLE_FOREST  = "TOGGLE_FOREST";
export const TOGGLE_AGRO  = "TOGGLE_AGRO";